# Introducción a la Programación para Ciencia de Datos
## Lenguaje de programación R
_Rocío Romero Zaliz_ - rocio@decsai.ugr.es

# Tipos de datos básicos

* numeric / integer
* logical
* complex
* character

In [1]:
1

[1] 1

In [2]:
print(1)

[1] 1


In [3]:
class(1)

[1] "numeric"

In [4]:
class(1.5)

[1] "numeric"

In [5]:
class(-3.78)

[1] "numeric"

In [6]:
TRUE

[1] TRUE

In [7]:
class(TRUE)

[1] "logical"

In [8]:
class(FALSE)

[1] "logical"

In [9]:
class(TRUE)
T <- 9
class(T)

[1] "logical"

[1] "numeric"

In [10]:
4 + 1.2i

[1] 4+1.2i

In [11]:
class(4 + 1.2i)

[1] "complex"

In [12]:
print("a")

[1] "a"


In [13]:
class("a")

[1] "character"

In [14]:
class("hola")

[1] "character"

In [15]:
class("adios") # Recomendado

[1] "character"

In [16]:
class('adios') # No recomendado

[1] "character"

In [ ]:
"hola" y "adios" # Error

In [ ]:
""hola" y "adios"" # Error

In [ ]:
'"hola" y "adios"' # Para este tipo de cosas se usan las comillas simples

In [17]:
1 / 0

[1] Inf

In [18]:
1 / Inf

[1] 0

In [19]:
0 / 0

[1] NaN

In [20]:
print(NULL)

NULL


In [21]:
?NULL

NULL                   package:base                    R Documentation

_T_h_e _N_u_l_l _O_b_j_e_c_t

_D_e_s_c_r_i_p_t_i_o_n:

     ‘NULL’ represents the null object in R: it is a reserved word.
     ‘NULL’ is often returned by expressions and functions whose value
     is undefined.

_U_s_a_g_e:

     NULL
     as.null(x, ...)
     is.null(x)
     
_A_r_g_u_m_e_n_t_s:

       x: an object to be tested or coerced.

     ...: ignored.

_D_e_t_a_i_l_s:

     ‘NULL’ can be indexed (see Extract) in just about any
     syntactically legal way: whether it makes sense or not, the result
     is always ‘NULL’.  Objects with value ‘NULL’ can be changed by
     replacement operators and will be coerced to the type of the
     right-hand side.

     ‘NULL’ is also used as the empty pairlist: see the examples.
     Because pairlists are often promoted to lists, you may encounter
     ‘NULL’ being promoted to an empty list.

     Objects with value ‘NULL

In [22]:
print(NA)

[1] NA


In [23]:
?NA

NA                    package:base                     R Documentation

'_N_o_t _A_v_a_i_l_a_b_l_e' / _M_i_s_s_i_n_g _V_a_l_u_e_s

_D_e_s_c_r_i_p_t_i_o_n:

     ‘NA’ is a logical constant of length 1 which contains a missing
     value indicator.  ‘NA’ can be coerced to any other vector type
     except raw.  There are also constants ‘NA_integer_’, ‘NA_real_’,
     ‘NA_complex_’ and ‘NA_character_’ of the other atomic vector types
     which support missing values: all of these are reserved words in
     the R language.

     The generic function ‘is.na’ indicates which elements are missing.

     The generic function ‘is.na<-’ sets elements to ‘NA’.

     The generic function ‘anyNA’ implements ‘any(is.na(x))’ in a
     possibly faster way (especially for atomic vectors).

_U_s_a_g_e:

     NA
     is.na(x)
     anyNA(x, recursive = FALSE)
     
     ## S3 method for class 'data.frame'
     is.na(x)
     
     is.na(x) <- value
     
_A_r_g_

In [24]:
NaN

[1] NaN

In [25]:
class(NaN)

[1] "numeric"

In [ ]:
?NaN

# Operadores aritméticos

In [ ]:
1 + 5

In [ ]:
5 - 4

In [ ]:
3 * 2.1

In [ ]:
7 / -4.3

In [ ]:
2 ^ 3

In [ ]:
2 ** -1/2 # Igual que ^

In [85]:
20 %% 3

[1] 2

In [27]:
3 %/% 2

[1] 1

# Operadores lógicos

In [ ]:
print(1 < 9.5)

In [ ]:
2.7 <= -5.3

In [ ]:
4.9 > 2

In [ ]:
4.9 >= 3

In [ ]:
5 == 5

In [ ]:
5 != 5

In [ ]:
!(5 == 5)

In [ ]:
(5 == 5) | (5 != 5)

In [ ]:
(5 == 5) & (5 != 5)

In [ ]:
1 == TRUE

In [ ]:
0 == FALSE

In [ ]:
7 == TRUE

In [28]:
as.logical(7) # WTF?

[1] TRUE

# Vectores
La funcion `c()` se usa para crear vectores

In [ ]:
c(1,5,8)

In [ ]:
print(c(1,5,8))

In [ ]:
print(c(1,2,3,4,3,5,4,5,2,3,9,-2,5.9,28,44,3,5,6,7,8,9,0,1,2,3,4,5,6,7,8,9,0))

In [ ]:
class(c(1,5,8))

In [ ]:
print(c(1.5,5,-8.5,5i))

In [ ]:
class(c(1.5,5,-8.5,5i))

In [ ]:
print(c("hola", "adios"))

In [ ]:
print(c("hola", 7))

In [ ]:
print(c(TRUE, FALSE, TRUE))

In [ ]:
print(c(T, F, T)) # Ojo cuidado!

In [ ]:
print(c(TRUE, 0, TRUE))

In [ ]:
print(as.logical(c(TRUE, 0, TRUE)))

In [ ]:
print(as.character(c(3,4,5)))

In [ ]:
is.character(as.character(c(3,4,5)))

In [ ]:
is.character(c(3,4,5))

Se pueden crear vectores dando un rango de valores usando `:`

In [ ]:
print(1:4)

In [ ]:
print(4:1)

In [ ]:
print(1.1:6.9)

In [ ]:
print(-1:5)

In [ ]:
vector("numeric", length = 10)

In [ ]:
print(vector("numeric", length = 10))

In [ ]:
print(vector("logical", length = 10))

<i>Atención que se vienen curvas...</i>

In [ ]:
print(1:3 + 4:6)

In [ ]:
print(1:3 + 4:7) # Warning! Recycling Rule

In [ ]:
print(1:3 * 4:6)

In [ ]:
print(1:3 - 4:6)

In [ ]:
print(1:3 / 4:6)

In [ ]:
1:3 == 4:6

In [ ]:
1:3 != 4:6

In [ ]:
1:3 < 4:6

In [ ]:
1:3 >= 4:6

In [ ]:
!(0:3)

### WTF? (Falling into the Floating Point Trap)
The R Inferno. Patrick Burns. https://www.burns-stat.com/pages/Tutor/R_inferno.pdf

In [ ]:
.1 == (.3 / 3)

In [ ]:
c(.3, .4 - .1, .5 - .2, .6 - .3, .7 - .4)

In [ ]:
unique(c(.3, .4 - .1, .5 - .2, .6 - .3, .7 - .4))

<i>R is good enough at hiding numerical error that it is easy to forget that it is there. Don’t forget...</i>

In [ ]:
1:5-1

In [ ]:
1:(5-1)

In [ ]:
10^2:6

In [ ]:
?Syntax

<i>Paréntesis... usad paréntesis...</i>

# Variables

In [ ]:
x <- 1 # A la variable x le asigno 1

In [ ]:
print(x)

In [ ]:
x = 5 # A la variable x le asigno 1 

In [ ]:
print(x)

<b>Atención:</b> `<-` no es lo mismo que `=`

In [ ]:
# Do not run!
foo(93, a = 47)
foo(93, a <- 47)

In [ ]:
# Do not run!
system.time(result <- Sys.sleep(5))
result <- system.time(Sys.sleep(5))

Seguimos...

In [ ]:
v <- c(2,6,8,10,-2,4.3)
print(v)

In [ ]:
print(v + 1) # Recycling Rule

In [ ]:
print(v * v)

In [ ]:
print(v == v)

In [ ]:
all(v == v) # Evalúa si todas las condiciones de un vector lógico son TRUE

In [ ]:
identical(v,v) # Comprueba si dos objetos son exactamente iguales en tipo, longitud, atributos y valores

In [ ]:
x <- c(1,1)
y <- c(1,1,1)
all(x == y)
identical(x, y)

In [ ]:
print(v)
print(c(3,2) %in% v)

In [ ]:
intersect(c(3,2), v)

In [ ]:
print(union(c(3,2), v))

In [ ]:
print(union(v, c(3,2)))

In [ ]:
print(setdiff(c(3,2), v))

In [ ]:
print(setdiff(v, c(3,2)))

In [ ]:
print(setdiff(abs(v), c(3,2)))

In [ ]:
print(v)
any(v > 2)

In [ ]:
all(v > 2)

# Más sobre vectores

In [ ]:
print(v)
print(v[1])

In [ ]:
print(v[0]) # Nada

In [ ]:
print(v[-1])

In [ ]:
print(v[-1:-2])

In [ ]:
print(v[c(1,4)])

In [ ]:
length(v)

In [ ]:
length(4)

In [ ]:
length("hola")

In [ ]:
nchar("hola") # Más sobre cadenas de caracteres más adelante...

In [ ]:
print(v)
v >= 0

In [ ]:
print(v[v >= 0])

In [ ]:
print(v[v < 0])

In [ ]:
print(v[v >= 0 & v <= 5])

In [ ]:
print(v)
v[c(TRUE,FALSE)]

In [ ]:
v[c(-1,-4)]

In [ ]:
sum(v)

In [ ]:
prod(v)

In [ ]:
min(v)

In [ ]:
max(v)

In [ ]:
w <- c(NULL, 3, NA, 7, NaN)
print(w)

In [ ]:
length(w)

In [ ]:
class(w)

In [ ]:
print(sum(w))

In [ ]:
sum(w, na.rm = TRUE)

In [ ]:
prod(w)

In [ ]:
prod(w, na.rm = TRUE)

In [ ]:
min(w)

In [ ]:
min(w, na.rm = TRUE)

In [ ]:
max(w)

In [ ]:
max(w, na.rm = TRUE)

In [ ]:
print(w)
is.na(w)

In [ ]:
is.nan(w)

Se pueden crear vectores tambien con `seq` o con `rep`

In [ ]:
print(1:6)

In [ ]:
?seq

In [ ]:
seq(from=12, to=30, by=3)

In [ ]:
seq(12, 30, 3) # seq(from=12, to=30, by=3)

In [ ]:
seq(-12, 30, 3.4)

In [ ]:
seq(1.1, 7, 10)

In [ ]:
print(seq(1.1, 7, length=10))

In [ ]:
seq()

In [ ]:
rep(8,4)

In [ ]:
rep(8,4.1) # El entero

In [ ]:
print(rep("a",4))

In [ ]:
rep(1:3, 5)

In [ ]:
length(rep(1:3, 5))

In [ ]:
?rep

In [ ]:
rep(c(5,12,13), 2)

In [ ]:
rep(c(5,12,13), each=2)

In [ ]:
letters

In [ ]:
LETTERS

In [ ]:
month.abb

In [ ]:
month.name

### WTF?

In [ ]:
print(x)
print(x == NA)

In [ ]:
class(x == NA)

In [ ]:
NA == NA

In [ ]:
3 == c(3, 1, 3, NA)

In [ ]:
is.na(c(3, 1, 3, NA))

In [ ]:
xnotnull <- 42
print(xnotnull == NULL)

In [ ]:
xnull <- NULL
print(xnull == NULL)

In [ ]:
is.null(xnull)

In [ ]:
x1 <- 10:1
print(x1)
x1 == c(4, 6)

In [ ]:
print(x1 == 4)
print(x1 == 6)
print(x1 == 4 | x1 == 6)
print(x1 == 4 & x1 == 6)


In [ ]:
print(x1 == 4 | 6)
as.logical(6)

In [ ]:
print(x1)
x1 == (4 | 6)

In [ ]:
4 | 6

<i>Esos paréntesis... ¡que no falten!</i>

In [ ]:
50 < "7"

In [ ]:
"50" < "7"

In [ ]:
length(x != 1)

In [ ]:
length(x) != 1

<i>No dejéis que R decida por vosotr@s...</i>

In [62]:
xna <- c(1, NA, 3, 2, 4, 2)
xna

[1]  1 NA  3  2  4  2

In [63]:
xna[xna == 2]

[1] NA  2  2

In [64]:
!is.na(xna)

[1]  TRUE FALSE  TRUE  TRUE  TRUE  TRUE

In [65]:
xna == 2

[1] FALSE    NA FALSE  TRUE FALSE  TRUE

In [66]:
xna[!is.na(xna) & xna == 2] # Analizar!

[1] 2 2

In [67]:
print(xna)
print(!is.na(xna))
print(xna == 2)

[1]  1 NA  3  2  4  2
[1]  TRUE FALSE  TRUE  TRUE  TRUE  TRUE
[1] FALSE    NA FALSE  TRUE FALSE  TRUE


In [68]:
which(xna == 2)

[1] 4 6

In [ ]:
xna[which(xna == 2)]

In [ ]:
x4 <- c(a=1, b=2, a=3)
print(x4)

In [ ]:
x4["a"]

In [ ]:
x4[names(x4) %in% "a"]

In [ ]:
print(c("missing value"=NA, "real string"="NA"))

### Ejercicios vectores
1) Crea un vector de números impares entre el 1 y el 30 (ambos inclusive)
2) Crea los siguientes vectores:
    * un vector del 1 al 20
    * un vector del 20 al 1
    * un vector que tenga el siguiente patrón 1,2,3,...,19,20,19,18,...,2,1
3) Crea una secuencia de números del 1 al 30 con un incremento de 0.5
4) Crea una secuencia que contenga las cuatro primeras letras del abecedario en minúscula 3 veces cada una (a a a b b b c c c d d d)
5) Crea el vector numérico `x` con los valores 2.3, 3.3, 4.3 y accede al segundo elemento del vector
6) Crea un vector numérico `z` que contenga los números del 1 al 10. Cambia la clase del vector forzando que sea de tipo carácter. Después cambia el vector `z` a numerico otra vez
7) Crea un vector numérico con valores no ordenados usando la función `sample()`. Una vez creado ordena el vector de forma ascendente usando la función `sort()`. ¿Si quisieras invertir el orden de los elementos del vector que función utilizarías?
8) Crea un vector `x` que contenga los elementos -5,-1,0,1,2,3,4,5,6. Escribe un código del tipo `x[algo]`, para extraer:
    * elementos de x menores que 0,
    * elementos de x menores o igual que 0,
    * elementos of x mayor o igual que 3,
    * elementos de x menor que 0 o mayor que 4,
    * elementos de x mayor que 0 y menor que 4,
    * elementos de x distintos de 0
9) Crea los siguientes vectores `x<-month.name[1:6]` y `z<-month.name[4:10]` a partir del vector original `month.name`. Recupera los valores idénticos entre los vectores x y z usando `%in%`
10) R permite extraer elementos de un vector que satisfacen determinadas condiciones usando la función `subset()`. Para el vector x <- c(6,1:3,NA,12) calcula los elementos mayores que 5 en x usando:
     * el filtrado normal, es decir, con el operador `>`
     * la función `subset()`

# Listas

Son estructuras de datos que permiten combinar elementos de diferente tipo y/o tamaño.

In [2]:
list_data <- list("Red", "Green", c(21,32,11), TRUE, 51.23, 119.1i)
print(list_data)

[[1]]
[1] "Red"

[[2]]
[1] "Green"

[[3]]
[1] 21 32 11

[[4]]
[1] TRUE

[[5]]
[1] 51.23

[[6]]
[1] 0+119.1i



In [3]:
class(list_data)

[1] "list"

In [4]:
print(list_data[5:6])

[[1]]
[1] 51.23

[[2]]
[1] 0+119.1i



In [5]:
print(list_data[6])

[[1]]
[1] 0+119.1i



In [6]:
class(list_data[6])

[1] "list"

In [7]:
print(list_data[[6]])

[1] 0+119.1i


In [8]:
class(list_data[[6]])

[1] "complex"

In [9]:
names(list_data) <- c("Colors", "Age", "Time")
print(list_data)

$Colors
[1] "Red"

$Age
[1] "Green"

$Time
[1] 21 32 11

$<NA>
[1] TRUE

$<NA>
[1] 51.23

$<NA>
[1] 0+119.1i



In [10]:
names(list_data) <- c("A", "B", "C", "E", "F", "G")
print(list_data)

$A
[1] "Red"

$B
[1] "Green"

$C
[1] 21 32 11

$E
[1] TRUE

$F
[1] 51.23

$G
[1] 0+119.1i



In [11]:
attributes(list_data)

$names
[1] "A" "B" "C" "E" "F" "G"

In [12]:
list_data[1]

$A
[1] "Red"

In [13]:
class(list_data["B"])

[1] "list"

In [14]:
class(list_data[["B"]])

[1] "character"

In [15]:
list_data[[1]] <- 5

In [16]:
list_data[[1]]

[1] 5

In [17]:
print(list_data)

$A
[1] 5

$B
[1] "Green"

$C
[1] 21 32 11

$E
[1] TRUE

$F
[1] 51.23

$G
[1] 0+119.1i



In [18]:
list_data[["C"]][2] <- "p"

In [19]:
print(list_data)

$A
[1] 5

$B
[1] "Green"

$C
[1] "21" "p"  "11"

$E
[1] TRUE

$F
[1] 51.23

$G
[1] 0+119.1i



In [20]:
print(list_data[1:3])

$A
[1] 5

$B
[1] "Green"

$C
[1] "21" "p"  "11"



In [21]:
print(list_data[c("A","E")])

$A
[1] 5

$E
[1] TRUE



In [22]:
print(list_data)

$A
[1] 5

$B
[1] "Green"

$C
[1] "21" "p"  "11"

$E
[1] TRUE

$F
[1] 51.23

$G
[1] 0+119.1i



In [23]:
print(unlist(list_data))

         A          B         C1         C2         C3          E          F 
       "5"    "Green"       "21"        "p"       "11"     "TRUE"    "51.23" 
         G 
"0+119.1i" 


In [24]:
class(unlist(list_data))

[1] "character"

In [25]:
num_list <- list(1,2,3,4,5)
day_list <- list("Mon","Tue","Wed", "Thurs", "Fri")
new_list <- c(num_list, day_list)
print(new_list)

[[1]]
[1] 1

[[2]]
[1] 2

[[3]]
[1] 3

[[4]]
[1] 4

[[5]]
[1] 5

[[6]]
[1] "Mon"

[[7]]
[1] "Tue"

[[8]]
[1] "Wed"

[[9]]
[1] "Thurs"

[[10]]
[1] "Fri"



In [26]:
new_list[[5]] <- NULL # Borrar opcion 1
print(new_list)

[[1]]
[1] 1

[[2]]
[1] 2

[[3]]
[1] 3

[[4]]
[1] 4

[[5]]
[1] "Mon"

[[6]]
[1] "Tue"

[[7]]
[1] "Wed"

[[8]]
[1] "Thurs"

[[9]]
[1] "Fri"



In [27]:
print(new_list[-5]) # Borrar opcion 2

[[1]]
[1] 1

[[2]]
[1] 2

[[3]]
[1] 3

[[4]]
[1] 4

[[5]]
[1] "Tue"

[[6]]
[1] "Wed"

[[7]]
[1] "Thurs"

[[8]]
[1] "Fri"



In [28]:
print(list(hola="Hola", 1, 3, adios = 5.6))

$hola
[1] "Hola"

[[2]]
[1] 1

[[3]]
[1] 3

$adios
[1] 5.6



### Ejercicios listas
1) Crea una lista llamada `mi_lista` que contenga los siguientes elementos: un vector numérico de 15 elementos, un vector de caracteres de 5 elementos y un vector de valores lógicos de 10 elementos todos TRUE
2) Dada la siguiente lista `my_list <- list(name="Fred", wife="Mary", no.children=3, child.ages=c(4,7,9))`:
    * Imprime los nombres de todos los componentes de la lista
    * Devuelve el segundo componente de la lista
    * Recupera el segundo elemento del cuarto componente de la lista 
    * Imprime la longitud del cuarto componente de la lista
    * Reemplaza el cuarto componente de la lista por un vector de 12 numeros del 1 al 12
    * Elimina el componente `wife`
    * Añade un componente más a la lista llamado `pepe`
3) Convertir un vector de 30 números postivos y negativos en una lista con [1ra componente: los 2 primeros elementos, 2da componente: los 5 siguientes pero como caracteres, 3ra componente: los elementos restantes que sean valores positivos, 4ta componente: una lista de caracteres con tu nombre y apellidos (ej: "Rocío" "Romero" "Zaliz")]
    * Una vez creado ponles nombre (ej: "1ro", "2do", etc)
    * Accede al tercer elemento por su nombre
    * Fusiona el primer y cuarto componente en un quinto componente y borra los originales
4) Crea una nueva lista cuyos componentes sean las listas de los ejericios anteriores (OJO: Su longitude debería ser 3)
5) Crea una nueva lista que concatene las listas de los tres primeros ejericios. ¿Qué longitud tiene?

# Matrices

* Las matrices son vectores con un atributo de dimensión. El atributo de dimensión es en sí mismo un vector entero de longitud 2 (nrow, ncol).
* Todas las columnas de una matriz deben tener el mismo tipo (numérico, carácter, etc.) y la misma longitud.

In [29]:
x <- 1:20
dim(x) <- c(5,4)
print(x)

     [,1] [,2] [,3] [,4]
[1,]    1    6   11   16
[2,]    2    7   12   17
[3,]    3    8   13   18
[4,]    4    9   14   19
[5,]    5   10   15   20


In [30]:
x

[,1] [,2] [,3] [,4]
[1,] 1     6   11   16  
[2,] 2     7   12   17  
[3,] 3     8   13   18  
[4,] 4     9   14   19  
[5,] 5    10   15   20

In [31]:
class(x)

[1] "matrix" "array"

In [32]:
matrix(nrow = 2, ncol = 3)

[,1] [,2] [,3]
[1,] NA   NA   NA  
[2,] NA   NA   NA

In [33]:
matrix(0, nrow = 2, ncol = 3)

[,1] [,2] [,3]
[1,] 0    0    0   
[2,] 0    0    0

In [34]:
matrix("a", nrow = 2, ncol = 3)

[,1] [,2] [,3]
[1,] a    a    a   
[2,] a    a    a

In [35]:
matrix(1:10, nrow = 3, ncol = 4)

Warning message in matrix(1:10, nrow = 3, ncol = 4):
“data length [10] is not a sub-multiple or multiple of the number of rows [3]”


[,1] [,2] [,3] [,4]
[1,] 1    4    7    10  
[2,] 2    5    8     1  
[3,] 3    6    9     2

In [36]:
matrix(1:10, nrow=3, ncol = 4, byrow=TRUE)

Warning message in matrix(1:10, nrow = 3, ncol = 4, byrow = TRUE):
“data length [10] is not a sub-multiple or multiple of the number of rows [3]”


[,1] [,2] [,3] [,4]
[1,] 1     2   3    4   
[2,] 5     6   7    8   
[3,] 9    10   1    2

In [37]:
matrix(1:12, nrow = 3)

[,1] [,2] [,3] [,4]
[1,] 1    4    7    10  
[2,] 2    5    8    11  
[3,] 3    6    9    12

In [38]:
matrix(1:12, ncol=3)

[,1] [,2] [,3]
[1,] 1    5     9  
[2,] 2    6    10  
[3,] 3    7    11  
[4,] 4    8    12

In [39]:
m <- matrix(1.1:12.1, nrow=3, byrow=FALSE)
rownames(m) <- c("A","B","C")
colnames(m) <- c("1","2","x","y")
m

1   2   x   y   
A 1.1 4.1 7.1 10.1
B 2.1 5.1 8.1 11.1
C 3.1 6.1 9.1 12.1

In [40]:
print(dim(m))

[1] 3 4


In [41]:
length(m)

[1] 12

In [42]:
rbind(1:5,11:15)

[,1] [,2] [,3] [,4] [,5]
[1,]  1    2    3    4    5  
[2,] 11   12   13   14   15

In [43]:
cbind(1:5,11:15)

[,1] [,2]
[1,] 1    11  
[2,] 2    12  
[3,] 3    13  
[4,] 4    14  
[5,] 5    15

In [44]:
m

1   2   x   y   
A 1.1 4.1 7.1 10.1
B 2.1 5.1 8.1 11.1
C 3.1 6.1 9.1 12.1

In [45]:
m[1,1]

[1] 1.1

In [46]:
print(m[1,])

   1    2    x    y 
 1.1  4.1  7.1 10.1 


In [47]:
print(m[,1])

  A   B   C 
1.1 2.1 3.1 


In [48]:
print(m[,])

    1   2   x    y
A 1.1 4.1 7.1 10.1
B 2.1 5.1 8.1 11.1
C 3.1 6.1 9.1 12.1


In [49]:
m[1:2,1:3]

1   2   x  
A 1.1 4.1 7.1
B 2.1 5.1 8.1

In [50]:
m[,c("1", "x")]

1   x  
A 1.1 7.1
B 2.1 8.1
C 3.1 9.1

In [51]:
m[,c(-1,-4)]

2   x  
A 4.1 7.1
B 5.1 8.1
C 6.1 9.1

In [52]:
m[,-"x"] # Error!

ERROR: Error in -"x": invalid argument to unary operator


In [53]:
c("x") %in% colnames(m) 

[1] TRUE

In [54]:
colnames(m) %in% c("x")

[1] FALSE FALSE  TRUE FALSE

In [55]:
m <- m[,!(colnames(m) %in% c("x"))]
m

1   2   y   
A 1.1 4.1 10.1
B 2.1 5.1 11.1
C 3.1 6.1 12.1

In [56]:
print(x[1,])
class(m[1,])

[1]  1  6 11 16


[1] "numeric"

In [57]:
m[1,,drop=FALSE]

1   2   y   
A 1.1 4.1 10.1

In [58]:
print(m[1,,drop=TRUE])

   1    2    y 
 1.1  4.1 10.1 


mx <- matrix(1:12, nrow=3, byrow=TRUE)
mx

In [60]:
mx[3, 2] <- 4
mx

[,1] [,2] [,3] [,4]
[1,] 1    2     3    4  
[2,] 5    6     7    8  
[3,] 9    4    11   12

In [61]:
mx[2, ] <- c(1,3) # Recycle!
mx

[,1] [,2] [,3] [,4]
[1,] 1    2     3    4  
[2,] 1    3     1    3  
[3,] 9    4    11   12

In [69]:
mx[1:2, 3:4] <- c(8,4,2,1)
mx

[,1] [,2] [,3] [,4]
[1,] 1    2     8    2  
[2,] 1    3     4    1  
[3,] 9    4    11   12

In [70]:
print(dim(mx))

[1] 3 4


In [71]:
dim(mx)[1]

[1] 3

In [72]:
dim(mx)[2]

[1] 4

In [73]:
ncol(mx)

[1] 4

In [74]:
nrow(mx)

[1] 3

In [75]:
t(mx)

[,1] [,2] [,3]
[1,] 1    1     9  
[2,] 2    3     4  
[3,] 8    4    11  
[4,] 2    1    12

In [76]:
diag(mx)

[1]  1  3 11

In [77]:
m * m

1    2     y     
A 1.21 16.81 102.01
B 4.41 26.01 123.21
C 9.61 37.21 146.41

In [78]:
m %*% m

1     2      y     
A 41.13  87.03 178.83
B 47.43 102.33 212.13
C 53.73 117.63 245.43

In [79]:
a <- attributes(m)
a

$dim
[1] 3 3

$dimnames
$dimnames[[1]]
[1] "A" "B" "C"

$dimnames[[2]]
[1] "1" "2" "y"

In [80]:
a$dimnames[[1]]

[1] "A" "B" "C"

In [81]:
class(attributes(m))

[1] "list"

# Arrays

Las matrices con más de dos dimensiones se llaman `array`

In [82]:
x <- 1:20
dim(x) <- c(2,5,2)
print(x)

, , 1

     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10

, , 2

     [,1] [,2] [,3] [,4] [,5]
[1,]   11   13   15   17   19
[2,]   12   14   16   18   20



In [83]:
a <- array(1:24, dim=c(3,4,2))
print(a) # Una matriz de 3 dimensiones

, , 1

     [,1] [,2] [,3] [,4]
[1,]    1    4    7   10
[2,]    2    5    8   11
[3,]    3    6    9   12

, , 2

     [,1] [,2] [,3] [,4]
[1,]   13   16   19   22
[2,]   14   17   20   23
[3,]   15   18   21   24



In [ ]:
a <- array(1:24, dim=c(3,4,2), 
           dimnames = list(c("ROW1","ROW2","ROW3"), 
                           c("COL1","COL2","COL3","COL4"), 
                           c("Matrix1","Matrix2")))
print(a)

In [ ]:
a[1,3,]

In [ ]:
a[1,3,1]

In [ ]:
print(a[3,,2])

In [ ]:
print(a[,,2])

### Ejercicios matrices y arrays
1) Dada la siguiente matriz:
<pre>laberinto <- matrix(c(
   "O", "X", "O", "O", "O",
   "O", "X", "X", "X", "O",
   "O", "O", "O", "O", "X",
   "X", "X", "X", "O", "X",
   "O", "O", "O", "O", "O"
 ), nrow = 5, byrow = TRUE)</pre>
    * Indique donde están las "X" usando la función `which`
    * Indique donde están las "X" usando la función `which` pero usando el parámetro `arr.ind`
    * Indique cuantos valores "X" hay en la matriz
    * Reemplace las "X" por 1 y los "O" por 0 y convierta la matrix en una matrix numérica
    * Indique si la matrix es simétrica
    * Cree una nueva matrix con los valores en las filas y columnas pares 
2) Crea una matriz que represente un Sudoku. Debe estar inicializada en NA. Luego rellenar solo un 10% de las casillas con un valor entre 1 y 9 (HINT: usa la función `sample`). No se preocupe de que sea un esquema válido (se pueden repetir valores en una fila por ejemplo... eso ya lo haremos más adelante... si acaso...)
3) Teniendo estas dos matrices:
<pre>matriz <- matrix(sample(1:9, 30,replace=TRUE), nrow=5)</pre>
<pre>mascara <- matrix(sample(c(TRUE,FALSE), 30, replace=TRUE), nrow=5)</pre>
    * Aplique la máscara a la matrix, en donde si la posicion en la máscara es FALSE entonces el resultado es 0 y sino se mantiene su valor
    * Calcule el producto de la matriz original por la matriz modificada traspuesta (NOTA: la matriz final será de 5x5)
4) Crea un array 5D llamado "mi_array5D" con las siguientes características, rellénalo con números enteros consecutivos comenzando desde 1:
    - Tamaño de la primera dimensión: 2 elementos
    - Tamaño de la segunda dimensión: 3 elementos
    - Tamaño de la tercera dimensión: 4 elementos
    - Tamaño de la cuarta dimensión: 5 elementos
    - Tamaño de la quinta dimensión: 6 elementos
    
    4.1) Accede a los siguientes elementos del array:
    * los elementos pares (analice la posición de esos valores en las 5 dimensiones)
    * estudiando el caso anterior muestre los elementos impares sin usar ningun tipo de condicional, igualdad o desigualdad
    
    4.2) Redimensiona el array para que tenga:
    - Tamaño de la primera dimensión: 6 elementos.
    - Tamaño de la segunda dimensión: 5 elementos.
    - Tamaño de la tercera dimensión: 4 elementos.
    - Tamaño de la cuarta dimensión: 3 elementos.
    - Tamaño de la quinta dimensión: 2 elementos.
5) Supongamos que tenemos un grafo no dirigido con 6 nodos etiquetados del 1 al 6, y las siguientes aristas:
    * Arista 1: (1, 2)
    * Arista 2: (1, 3)
    * Arista 3: (2, 4)
    * Arista 4: (2, 5)
    * Arista 5: (3, 6)
    * Arista 6: (4, 5)
    
    Crea una matriz de adyacencia "matriz_adyacencia" en R para representar este grafo. En una matriz de adyacencia, las filas y columnas representan los nodos, y un valor 1 indica que existe una arista entre los nodos correspondientes, mientras que un valor 0 indica la ausencia de una arista.
    * Calcula el grado del nodo 4 en el grafo. El grado de un nodo es la cantidad de aristas que inciden en él
    * Encuentra todos los nodos adyacentes del nodo 2
    * Cuenta la cantidad de nodos que tiene una arista hacia si mismos (self-loop)

# Factores (variables nominales)
Los factores son vectores para valores categóricos
* Levels: refers to the input values
* Labels: refers to the output values of the new factor

In [ ]:
Pain <- c(0,3,2,2,1)
Pain

In [ ]:
SevPain <- factor(c(0,3,2,2,1), levels=c(0,1,2,3), labels=c("none","mild","medium","severe"))
class(SevPain)

In [ ]:
SevPain

In [ ]:
directions <- c("North", "East", "South", "South")
factor(directions)

In [ ]:
factor(directions, levels=c("North", "East", "South", "West"), labels=c("N","E","S","W"))

In [ ]:
table(factor(directions))

# Factores ordenados (variables ordinales)

In [ ]:
status <- c("Lo", "Hi", "Med", "Med", "Hi")
ordered.status <- factor(status, levels=c("Lo", "Med", "Hi"), ordered=TRUE)
print(ordered.status)

In [ ]:
table(status)

In [ ]:
table(ordered.status)

 ### WTF?

In [ ]:
f <- factor(c(101,6,8,9,6,103))
print(f)
is.numeric(f)

In [ ]:
as.numeric(f)

In [ ]:
as.numeric(levels(f))

In [ ]:
as.numeric(as.character(f))

In [ ]:
ff <- factor(c("AA", "BA", "CA"))
ff[1:2]

In [ ]:
ff[1:2, drop=TRUE] # Borrar opcion 1

In [ ]:
factor(ff[1:2]) # "Borrar" opcion 2

In [ ]:
f1 <- factor(c("AA", "BA", NA, "NA"))
f1

In [ ]:
f1 <- factor(c("AA", "BA", NA, "NA"), exclude=NULL)
f1

### Ejercicios factores
1) Crea un factor llamado "fact_puntuacion" que contenga puntuaciones de 1 al 5 para 1000 productos. Utiliza la función `summary()` para obtener un resumen de la distribución de puntuaciones. ¿Qué puedes deducir del tipo de aleatoriedad usada en `sample`? ¿Es normal, uniforme, ...?
2) Crea un factor ordenado para edades entre 0 y 100 de 100 personas. Utiliza la función `cut` para generar 3 nieveles separados. Ahora reetiqueta el factor como "joven", "adulto" o "anciano". Muestra la frecuencia de cada nivel.
3) Crea un factor para el siguiente vector teniendo en cuenta que los niveles posibles son todas las letras de la "A" a la "Z":
<pre>v <- c("A","I", "I", "J", "A", "Z", "X")</pre>
    * Modifica una de las "I" por una "F"
    * Agrega una nueva "A" en última posición
    * Indica las letras que aparecen en el factor ordenadas por su frecuencia, empezando con la menos frecuente

# Data Frames

Un marco de datos o data frame es una matriz generalizada, donde las diferentes columnas pueden tener diferentes tipos de datos (numérico, carácter, factor, etc.).

Por ejemplo, vectores y/o factores de la misma longitud que están relacionados "transversalmente", de forma que los datos en la misma posición proceden de la misma unidad experimental (sujeto, animal, etc.).

In [ ]:
S <- as.factor(c("F","M","M","F"))
Patients <- data.frame(age=c(31,32,40,50), sex=S)
Patients

In [ ]:
employee <- c("John Doe","Peter Gynn","Jolie Hope")
salary <- c(21000, 23400, 26800)
startdate <- as.Date(c("2010-11-1","2008-3-25","2007-3-14"))

employ.data <- data.frame(employee, salary, startdate)
employ.data

In [ ]:
str(employ.data)

In [ ]:
employ.data <- data.frame(employee, salary, startdate, stringsAsFactors=TRUE)
employ.data

In [ ]:
ncol(employ.data)

In [ ]:
nrow(employ.data)

In [ ]:
length(employ.data) # ¡Cuidado!

In [ ]:
summary(employ.data)

In [ ]:
employ.data[1,1]

In [ ]:
employ.data[1,]

In [ ]:
employ.data[,1]

In [ ]:
employ.data$employee

In [ ]:
rbind(employ.data, c("John Doe", 50000, "1990-11-1"))

In [ ]:
rbind(employ.data, c("Rocio Romero", 50000, "1990-11-1")) # Error

In [ ]:
rbind(employ.data, c("John Doe", 50000)) # Error

In [ ]:
# Crear los datos para el dataframe
year <- c(2000, 2020, 2021, 2021, 2022, 2022, 2023, 2023, 2024, 2024)
country <- c("Argentina", "Brasil", "Chile", "Colombia", "Ecuador", "Perú", "México", "Uruguay", "Paraguay", "Bolivia")
valor1 <- c(100, 120, 90, 110, 80, 105, 115, 95, 125, 75)

# Crear el dataframe
data1 <- data.frame(year, country, valor1)
data1

In [ ]:
# Crear los datos para el dataframe
country <- rep(c("Argentina", "Brasil", "Chile"), each = 1, times = 5)
year <- c(rep(seq(2000, 2006, by = 1), each = 2), 2020)
valor2 <- runif(15, min = 1, max = 100) # Valores aleatorios entre 1 y 100

# Crear el dataframe
data2 <- data.frame(country, year, valor2)
data2

In [ ]:
?merge

In [ ]:
merge(data1, data2, by = c("country", "year")) # conserva sólo las observaciones coincidentes

In [ ]:
merge(data1, data2, by = c("country", "year"), all.x = TRUE)

In [ ]:
merge(data1, data2, by = c("country", "year"), all.y = TRUE)

In [ ]:
merge(data1, data2, by = c("country", "year"), all = TRUE)

### Ejercicios data frames
1) Usando el dataset `mtcars`:
    * Muestra las 5 primeras filas
    * Presenta un resumen del datasest
    * Haz una copia del dataset y:
        * Convierte la variables "cyl", "gear" y "carb" en factores
        * Convierte las variables "vs" y "am" en lógicas
        * Muestra solo los coches con una potencia ("hp") mayor a 100
        * Crea un nuevo data frame llamado coches_seleccionados que incluya solo las columnas "mpg", "cyl", "hp" y "qsec" del dataset
        * Calcula el resumen estadístico (media, mediana, desviación estándar, etc.) de la columna "mpg" (millas por galón) para todos los coches en el dataset
        * Idem para "cyl" (número de cilindros)
        * Calcula la cantidad total de coches para cada valor único en la columna "cyl" (número de cilindros)
        * Encuentra el modelo de coche con la mayor potencia ("hp") y muestra su información completa
        * Calcula el promedio de potencia de los coches con 8 cilindros
2) Usando el dataset `Cars93` del paquete `MASS` y el dataset `mtcars`:
    * Agrega una columna al dataset de `mtcars` que contenga la marca y modelo de cada coche
    * Combina los dos dataset por modelo y marca del coche solo para aquellos modelos presentes en ambos datasets. ¿Coinciden los demás valores?
3) Supongamos que tienes dos dataframes con información sobre estudiantes de dos cursos diferentes. Cada data frame contiene tres columnas: "Nombre", "Edad" y "Promedio".
<pre>
curso_a <- data.frame(
    Nombre = c("Juan", "María", "Carlos"),
    Edad = c(20, 22, 21),
    Promedio = c(85, 92, 78))
</pre><pre>
curso_b <- data.frame(
       Nombre = c("Ana", "Luis", "Sofía", "Lourdes"),
       Edad = c(19, 23, 20, 21),
       Promedio = c(88, 90, 85, 80))
</pre>
* Combina los dos dataframes en uno solo llamado todos_los_estudiantes
* Agrega una nueva columna llamada "Curso" al dataframe todos_los_estudiantes que indicar a qué curso pertenece cada estudiante ("A" o "B")